import axios from "axios";

const BACKEND_URL = "http://172.23.128.1:3000";

export const httpStoreExpense = async (expenseData) => {
  const response = await axios.post(
    `${BACKEND_URL}/expenses.json`,
    expenseData
  );
  const id = response.data.name; // firebase specific - this is the ID for the added expense generated by Firebase

  return id;
};

export const httpFetchExpense = async () => {
  const response = await axios.get(`${BACKEND_URL}/expenses.json`);

  const expenses = [];

  for (const key in response.data) {
    const expenseObj = {
      id: key,
      amount: response.data[key].amount,
      date: new Date(response.data[key].date),
      description: response.data[key].description,
    };
    expenses.push(expenseObj);
  }

  return expenses;
};

export const httpUpdateExpense = (id, expenseData) => {
  return axios.put(`${BACKEND_URL}/expenses/${id}.json`, expenseData);
};

export const httpDeleteExpense = (id) => {
  return axios.delete(`${BACKEND_URL}/expenses/${id}.json`);
};

export const httpAddWallet = async (walletData, token) => {
  const response = await axios.post(`${BACKEND_URL}/wallets`, walletData, {
    headers: {
      Authorization: `Bearer ${token}`,
    },
  });

  return response.data;
};

export const httpFetchWallet = async (token) => {
  const response = await axios.get(`${BACKEND_URL}/wallets/user`, {
    headers: {
      Authorization: `Bearer ${token}`,
    },
  });
  
  return response.data;
};
